### ISSUE TITLE
Failure after installing on fedora 34

### ISSUE THREAD

**Issue by dvalinrh** [sourabhtk37/Quisby#9]
poetry run quisby -h
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dvalin/zath_dev/Quisby/quisby/quisby.py", line 9, in <module>
    from quisby.sheet.sheetapi import sheet
  File "/home/dvalin/zath_dev/Quisby/quisby/sheet/sheetapi.py", line 1, in <module>
    from googleapiclient.discovery import build
ModuleNotFoundError: No module named 'googleapiclient'

Installed 
php-google-apiclient1.noarch
and
python3-google-api-client.noarch

still have same issure

**Comment by sourabhtk37** [comment]
Hi @dvalinrh 

I guess the required python packages/modules weren't installed automatically. 

`pip install --upgrade google-api-python-client`
This would install the package that have the `googleapiclient` module.  I guess some more packages might be reported missing. For that please run `poetry install` (given [poetry is installed](https://python-poetry.org/docs/)), it will install the correct dependencies defined in the `pyproject.toml` and `poetry.lock` files.

**Comment by dvalinrh** [comment]
Ok,. that clears out the issue (please update the README).

Next issue
dvalin@localhost Quisby]$ poetry run quisby process --os-type rhel --os-release rhel_8.4 --cloud-type aws  lin_file
INFO:root:process result: linpack/amazon/i3en.24xlarge/results_linpack.csv

INFO:root:process result: linpack/amazon/m5.24xlarge/results_linpack.csv

INFO:root:process result: linpack/amazon/m5.xlarge/results_linpack.csv

INFO:root:process result: linpack/amazon/i3en.xlarge/results_linpack.csv

INFO:root:process result: linpack/rhel/i3en.24xlarge/results_linpack.csv

INFO:root:process result: linpack/rhel/m5.24xlarge/results_linpack.csv

INFO:root:process result: linpack/rhel/m5.xlarge/results_linpack.csv

INFO:root:process result: linpack/rhel/i3en.xlarge/results_linpack.csv

INFO:root:process result: linpack/ubuntu/i3en.24xlarge/results_linpack.csv

INFO:root:process result: linpack/ubuntu/m5.24xlarge/results_linpack.csv

INFO:root:process result: linpack/ubuntu/m5.xlarge/results_linpack.csv

INFO:root:process result: linpack/ubuntu/i3en.xlarge/results_linpack.csv

https://docs.google.com/spreadsheets/d/

Do not see anything appear in my folders (sheets).  Logged into gmail with both my Redhat account and my private email.  Do not see the results any place.
Been about 10 minutes.

**Comment by sourabhtk37** [comment]
Seems like missing data. If you don't see spreadsheet then it must be
missing data or the format of the data is changed which is not supported.

**Comment by dvalinrh** [comment]
Data is present, sample
hyper_config:sockets:threads:unit:MB/sec:cpu_affin
hyper_yes_1_socket:1:2:GFlops:224:0,1
hyper_yes_1_socket:1:4:GFlops:224:2,3,0,1

Ran with just 1 file also, same thing
test: results_linpack
linpack/cloud_os/cloud_sys/results_linpack.csv

Know something is not set up right, question is what, and then updating the documentation  accordingly.

Also, if that is the case, Quisby needs to spit out an error message it is not uploading anything.  Silent failures is not good.
